# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
